### ISSUE TITLE
it is can be dynamic with HA without restart

### ISSUE THREAD

**Issue by rt400** [tgerla/appdaemon-apps#1]
hi..
you generic timer code is amazing..
its looks very useful for me..
first i want to know is which yaml file should be add to use it .?
second , is there is a way that can be responsive in HA ?
like take pic of mechanical 24 H clock and when i click some ping on him it will be set on the times entirys..

**Comment by tgerla** [comment]
Hi! I'm glad you found the timer code. I am not sure I understand your last question. I think you are asking if there is a web-based method to set the timer by clicking on a picture of a clock. Unfortunately I am not sure how to do that, but it is a very good idea!

For the first question: you will need to find your config/appdaemon/apps/apps.yaml file, and add a section that looks like:

```
generic_timer:
   module: generic_timer
   class: GenericTimer
   entries:
     - entity: switch.crawlspace_fan
       times:
         - ontime: "23:00"
           offtime: "7:00"
```

You can have multiple ontime/offtime entries.

I hope this helps!
